#!/bin/bash
# sign-efi-binary-test.sh — REAL exercise of gen-efi.sh's sign_efi_binary()
# (fix #3: verify the freshly-signed TMP file BEFORE moving it over the live
# file, instead of moving-then-verifying).
#
# Run as root inside the nspawn @blue slot, where the real MOK keys already
# exist (generated by gen-efi during bootstrap). Programmatically extracts
# the ACTUAL function body from the currently-installed /usr/local/bin/gen-efi
# (the edited copy) with sed.
#
# Simulates a "successful-but-bad" sbsign: a stub `sbsign` on PATH that exits
# 0 (claims success) but writes an UNSIGNED copy of the input as its output
# — exactly the scenario the original bug could not protect against, since it
# moved the signed tmp file over the live file BEFORE calling sbverify.
set -uo pipefail

FAIL=0
pass(){ echo "PASS: $1"; }
fail(){ echo "FAIL: $1"; FAIL=1; }

SRC=/usr/local/bin/gen-efi
MOK_KEY=/etc/secureboot/keys/MOK.key
MOK_CRT=/etc/secureboot/keys/MOK.crt
[[ -f "$SRC" ]] || { echo "FATAL: $SRC not found"; exit 2; }
[[ -f "$MOK_KEY" && -f "$MOK_CRT" ]] || { echo "FATAL: MOK keys not found — run bootstrap first"; exit 2; }

FUNC_BODY=$(sed -n '/^sign_efi_binary() {/,/^}/p' "$SRC")
[[ -n "$FUNC_BODY" ]] || { echo "FATAL: could not extract sign_efi_binary() from $SRC"; exit 2; }
echo "=== Extracted $(echo "$FUNC_BODY" | wc -l) lines for sign_efi_binary() from the live installed binary ==="

log() { echo "[test-log] $*"; }
log_warn() { echo "[test-log][WARN] $*"; }
error_exit() { echo "[test-log][ERROR] $*"; exit 1; }

eval "$FUNC_BODY"
declare -f sign_efi_binary >/dev/null || { echo "FATAL: eval did not define sign_efi_binary"; exit 2; }

WORKDIR=/root/sign-efi-test
rm -rf "$WORKDIR"; mkdir -p "$WORKDIR/fakebin"
cp /usr/lib/systemd/boot/efi/systemd-bootx64.efi "$WORKDIR/testfile.efi"
cp "$WORKDIR/testfile.efi" "$WORKDIR/testfile.efi.golden"

echo ""
echo "########## Sanity: test file starts out NOT signed with MOK_CRT ##########"
if sbverify --cert "$MOK_CRT" "$WORKDIR/testfile.efi" &>/dev/null; then
    echo "FATAL: test fixture is already signed — pick a different source binary"
    exit 2
fi
pass "Sanity: fresh systemd-bootx64.efi copy is unsigned, as expected"

echo ""
echo "########## Test 1: sbsign 'succeeds' but produces an invalid (unsigned) result ##########"
cat > "$WORKDIR/fakebin/sbsign" <<'EOF'
#!/bin/bash
# Fake sbsign: parses --output <path> <input>, and instead of actually
# signing, just copies the UNSIGNED input to the output path, then claims
# success (exit 0) -- simulating a corrupted/truncated real-world signing
# failure that nonetheless returns rc=0.
out=""
input=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --output) out="$2"; shift 2 ;;
        --key|--cert) shift 2 ;;
        *) input="$1"; shift ;;
    esac
done
cp "$input" "$out"
exit 0
EOF
chmod +x "$WORKDIR/fakebin/sbsign"

(
    export PATH="$WORKDIR/fakebin:$PATH"
    which sbsign
    sign_efi_binary "$WORKDIR/testfile.efi"
)
subshell_rc=$?

if [[ $subshell_rc -eq 0 ]]; then
    fail "Test 1: sign_efi_binary returned success (0) despite sbverify-should-have-failed scenario!"
else
    pass "Test 1: sign_efi_binary exited non-zero (error_exit fired) when the freshly-signed tmp file failed verification"
fi

if cmp -s "$WORKDIR/testfile.efi" "$WORKDIR/testfile.efi.golden"; then
    pass "Test 1: LIVE file was left byte-for-byte unchanged — bad signature never replaced it"
else
    fail "Test 1: LIVE file was MODIFIED despite failing verification — verify-before-replace is broken!"
fi

if ls "$WORKDIR"/testfile.efi.signed.tmp "$WORKDIR"/testfile.efi.orig.tmp &>/dev/null; then
    fail "Test 1: tmp files were left behind: $(ls "$WORKDIR"/testfile.efi*.tmp 2>/dev/null)"
else
    pass "Test 1: no leftover .tmp files"
fi

echo ""
echo "########## Test 2: real sbsign (unstubbed) on the same still-unsigned file succeeds ##########"
sign_efi_binary "$WORKDIR/testfile.efi"
rc=$?
if [[ $rc -eq 0 ]] && sbverify --cert "$MOK_CRT" "$WORKDIR/testfile.efi" &>/dev/null; then
    pass "Test 2: real sbsign path still works — file is now validly signed with MOK_CRT"
else
    fail "Test 2: real signing path broken (rc=$rc, sbverify $(sbverify --cert "$MOK_CRT" "$WORKDIR/testfile.efi" 2>&1))"
fi

echo ""
echo "=== SIGN_EFI_BINARY TEST SUMMARY: FAIL=$FAIL ==="
exit "$FAIL"
