#!/usr/bin/env python3
"""Generate `app-scripts/cassini-tour.actions` from Cassini's own SECTIONS.

**Why this exists.** The tour was a hand-maintained list of
`click-element=^Title$` lines, and it had fallen 25 pages behind: 32 of 57
pages were toured. Nothing failed when a page was added — the tour simply did
not grow, so a new page shipped untoured and the gap was invisible. That is the
same rot this workspace keeps paying for in a hardcoded count: the literal and
the thing it describes drift, and the file that should catch it asserts against
the literal.

So the literal is generated, and `tests/cassini-tour-covers-every-page.py`
fails if the checked-in file differs from what this produces. Adding a page now
fails a self-test until the tour is regenerated, which is the point.

**Why click-element and not `--section`.** The tour is ONE app launch walking the
sidebar, and `--section` is read once at startup, so it cannot switch pages in a
running instance. Driving all 57 ids would mean 57 launches. (Activating the
`show-section` action over D-Bus would do it in one - and cannot: the action is
listed by `DescribeAll`, but supplying its `av` argument is not reachable from
PyGObject. See shani-testbed/AGENTS.md for the seven routes that were measured.)

**Sidebar scrolling.** GTK4 has no AT-SPI `scroll_to`, so `click-element` on a
row below the fold falls back to focusing it, which GTK4 scrolls into view. The
rows are matched on their exact title, so a truncated or icon-only row is a
miss rather than a wrong click.

    usage: generate-cassini-tour.py [--repo=/path/to/shani-cassini] [--check]
"""
from __future__ import annotations

import argparse
import os
import sys

HEADER = """\
# cassini-tour — every Shani Cassini page, driven like a user, on the real
# image (its Python, PyGObject, GTK4, libadwaita):
#   app <slot> --run=shani-cassini --strict --script=app-scripts/cassini-tour.actions
# Each page: open it from the sidebar by its accessible name, give it time to
# load its real data, require the content to have CHANGED from the page before
# (a page that renders nothing is not "loaded"), and require every on-screen
# control to have an accessible name. At the end: no GLib/GTK criticals or
# warnings in the app's log, then 40 seeded random clicks it must survive.
# --strict (G_DEBUG=fatal-criticals) turns the first critical into a crash.
#
# GENERATED by app-scripts/generate-cassini-tour.py from the app's own
# SECTIONS — do not hand-edit. `tests/cassini-tour-covers-every-page.py`
# fails if this file and the sidebar disagree, so a page added without being
# toured is a red self-test rather than a silent gap.
"""

# Per-page settle time. Pages that read several tools need longer than one that
# reads one; the first and last entries of each subject get the extra second
# because the first launch of an app also pays GTK's own start-up.
DEFAULT_SETTLE = 3


def pages(repo: str):
    """(id, title) for every page in the sidebar, in the order it appears."""
    src = os.path.join(repo, "src")
    if src not in sys.path:
        sys.path.insert(0, src)
    from shani_cassini.notebook import SECTIONS
    out = []
    for _group, subjects in SECTIONS:
        for _subject, entries in subjects:
            for entry in entries:
                out.append((entry[1], entry[2]))
    return out


def render(entries, settle: int = DEFAULT_SETTLE) -> str:
    lines = [HEADER.rstrip("\n"), ""]
    lines += [
        "wait-window=Shani Cassini:90",
        f"sleep={settle + 2}",
        "screenshot",
        "a11y-lint",
    ]
    previous_id = None
    for index, (pid, title) in enumerate(entries):
        lines.append(f"# --- {title} ({pid})")
        lines.append(f"click-element=^{_re(title)}$")
        # A page that reads a subprocess needs longer than one that reads a file.
        nap = settle + (2 if index in (0, len(entries) - 1) else 0)
        lines.append(f"sleep={nap}")
        if previous_id is not None:
            # "must have changed" — a page that renders nothing is not loaded.
            lines.append(f"expect-changed=@out/tour-{previous_id}.png:0.5")
        shot = f"tour-{pid}.png"
        lines.append(f"screenshot=@out/{shot}")
        lines.append("a11y-lint")
        # The ID, not the filename: storing the filename produced
        # `tour-tour-overview.png.png` on the next line, because the name is
        # built from the id again here.
        previous_id = pid
    lines += [
        "# --- and the app must survive being clicked at",
        "expect-clean-log",
        "monkey=40",
        "quit",
        "",
    ]
    return "\n".join(lines)


def _re(text: str) -> str:
    """Escape a page title for the `^...$` regex the actions use."""
    return text.replace("(", r"\(").replace(")", r"\)")


def main() -> int:
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", default=os.path.join(here, "..", "shani-cassini"))
    ap.add_argument("--out", default=os.path.join(here, "app-scripts",
                                                   "cassini-tour.actions"))
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if --out differs from what would be generated")
    args = ap.parse_args()

    entries = pages(os.path.realpath(args.repo))
    if not entries:
        sys.stderr.write(f"no pages found under {args.repo}\n")
        return 2
    want = render(entries)

    if args.check:
        try:
            have = open(args.out, encoding="utf-8").read()
        except OSError as exc:
            sys.stderr.write(f"cannot read {args.out}: {exc}\n")
            return 1
        if have != want:
            sys.stderr.write(
                f"{args.out} is out of date with Cassini's sidebar.\n"
                f"  it covers {have.count('click-element=')} pages; "
                f"the app has {len(entries)}.\n"
                f"  regenerate: python3 {os.path.relpath(__file__, here)}\n")
            return 1
        print(f"cassini-tour.actions covers all {len(entries)} pages")
        return 0

    with open(args.out, "w", encoding="utf-8") as handle:
        handle.write(want)
    print(f"wrote {args.out}: {len(entries)} pages")
    return 0


if __name__ == "__main__":
    sys.exit(main())
